### ISSUE TITLE
Use PostCSS 4.1 API

### ISSUE THREAD

**Issue by TrySound** [Rycochet/postcss-epub#4]
PostCSS Plugin Guidelines are mandatory right now. Because all of rules are about ecosystem health.

**Comment by Rycochet** [comment]
Done, thanks for pointing this out :-)

**Comment by TrySound** [comment]
Minor version up, please. API was compatibly extented.

**Comment by Rycochet** [comment]
Doesn't break previous API, so no need to change it

**Comment by TrySound** [comment]
1. MAJOR version when you make incompatible API changes,
1. MINOR version when you add functionality in a backwards-compatible manner, and
1. PATCH version when you make backwards-compatible bug fixes.

**Comment by Rycochet** [comment]
Gah, that's what I get when only taking 5 minutes from the work day to do these things (we only bump minor for API breaking changes at work)
